name: Release
on:
  push:
    paths-ignore:
      - "**/renovate.json"
      - README.md
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.OBLAKBOT_PAT }}
      - name: Import GPG keys
        uses: crazy-max/ghaction-import-gpg@v6
        id: gpg
        with:
          gpg_private_key: ${{ secrets.OBLAKBOT_GPG_KEY }}
          passphrase: ${{ secrets.OBLAKBOT_GPG_PASS }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/github
            @semantic-release/exec
        env:
          token: ${{ secrets.OBLAKBOT_PAT }}
